### ISSUE TITLE
Error serializing with imported getServerSideProps

### ISSUE THREAD

**Issue by cellulosa** [orionmiz/next-superjson-plugin#1]
hi @orionmiz and thank you for the plugin, it works perfectly when `getServerSideProps` sits on the same page file.

However, I am importing a common `getServerSideProps` from `../utils/getServerSideProps.tsx` and it that case the seralisation does not happen:

```error - SerializableError: Error serializing `.fallback["/api/state"].createdAt` returned from `getServerSideProps` in "/".```

Is that the intended behaviour? Is there a way to add a path to be processed?

Thank you

**Comment by orionmiz** [comment]
Thanks for reporting!

First, I designed optimization preventing nested SuperJSON wrapping
like [this case](https://github.com/orionmiz/next-superjson-plugin/blob/main/tests/fixture/skip/export-from/code.js) assuming that gSSP & gSP functions are **in a page file**

For this reason, I recommend you to place those functions in the page file.

But I'm planning to develop an option disabling optimization
for users who wants to seperate gSSP & gSP functions into other files.

**Comment by cellulosa** [comment]
Cool in that case I moved `getServerSideProps` into a page file and call it from there from other pages. Thanks ever so much for the plugin and for the quick reply too! 🙌

**Comment by jbwc** [comment]
Would also prefer to be able to import composable functions from other files
